### ISSUE TITLE
Avoidable crash when using SIRIUS

### ISSUE THREAD

**Issue by flomnes** [rte-france/or-tools#38]
### Configuration
Python 3.8
Ubuntu 20.04
 [ortools 9.2-rte1.2 Sirius + XPRESS](https://github.com/rte-france/or-tools/releases/download/v9.2-rte1.2/ortools_python-3.8_ubuntu-20.04_sirius_xprs.zip)

### Minimal python script
```py
from ortools.linear_solver import pywraplp as pylp
solver=pylp.Solver.CreateSolver("sirius")

x=solver.NumVar(0, solver.infinity(), 'x')
y=solver.NumVar(-5, 10, 'y')

solver.Minimize(3*x+2*y)
```

### GDB backtrace
```gdb
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7de1859 in __GI_abort () at abort.c:79
#2  0x00007ffff529e911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff52aa38c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff52aa3f7 in std::terminate() ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff52aa6a9 in __cxa_throw ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff58bbf70 in operations_research::SiriusInterface::SetObjectiveOffset(double) [clone .cold] ()
   from /home/omnesflo/.local/lib/python3.8/site-packages/ortools/linear_solver/../../ortools/.libs/libortools.so.9
#7  0x00007ffff71826bd in _wrap_Objective_SetOffset ()
   from /home/omnesflo/.local/lib/python3.8/site-packages/ortools/linear_solver/_pywraplp.so
#8  0x00000000005f5f1a in PyCFunction_Call ()
#9  0x00000000005f6a46 in _PyObject_MakeTpCall ()
#10 0x0000000000570a1f in _PyEval_EvalFrameDefault ()
#11 0x00000000005f6226 in _PyFunction_Vectorcall ()
#12 0x000000000056b5e0 in _PyEval_EvalFrameDefault ()
#13 0x00000000005f6226 in _PyFunction_Vectorcall ()
#14 0x000000000056b5e0 in _PyEval_EvalFrameDefault ()
#15 0x00000000005696da in _PyEval_EvalCodeWithName ()
```

### Probable cause

Unhandled exception is raised because the Sirius interface does not define method `SetObjectiveOffset`.
```cpp
void SiriusInterface::SetObjectiveOffset(double value) {
    // Changing the objective offset is O(1), so we always do it immediately.
    InvalidateSolutionSynchronization();
    throw std::logic_error("Not implemented");
    //FIXME CHECK_STATUS(SRSsetobjoffset(mLp, value));
}
```
See **or-tools/ortools/linear_solver/sirius_interface.cc:577**.

### Possible solutions
- Implement `SetObjectiveOffset`, removing the need to throw an exception
- Remove the exception throw, considering that in most cases, the offset is 0 anyway.

**Comment by flomnes** [comment]
Possible fix https://github.com/rte-france/sirius-solver/pull/10
